// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApg30kE1sughX88aC2KxxcHFXsRAjs8lM',
    appId: '1:554119775854:android:f511d70f26f037aaa6087f',
    messagingSenderId: '554119775854',
    projectId: 'checkpoint-68ad3',
    storageBucket: 'checkpoint-68ad3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAx7wYpIQBi2DYjcyQ2JaqgWocGAjRU48o',
    appId: '1:554119775854:ios:a6a194a00f4ce70aa6087f',
    messagingSenderId: '554119775854',
    projectId: 'checkpoint-68ad3',
    storageBucket: 'checkpoint-68ad3.firebasestorage.app',
    iosBundleId: 'com.example.checkPoint',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPnr43dsqLw4f1nm0HAClpwrdwyvUf8jw',
    appId: '1:554119775854:web:2b1a4f2b106792b0a6087f',
    messagingSenderId: '554119775854',
    projectId: 'checkpoint-68ad3',
    authDomain: 'checkpoint-68ad3.firebaseapp.com',
    storageBucket: 'checkpoint-68ad3.firebasestorage.app',
    measurementId: 'G-CLXZCNCZ7V',
  );
}
